# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_article_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
    ]
