# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='art_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='art',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app1.article'),
            preserve_default=False,
        ),
    ]
