# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20160313_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='detail',
            new_name='content',
        ),
    ]
