# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_cats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cats',
        ),
    ]
