# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_article_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cats',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='blog.cat'),
            preserve_default=False,
        ),
    ]
