# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='art',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
