# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app06', '0004_auto_20160311_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
