# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app06', '0010_auto_20160317_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='cat',
            new_name='user',
        ),
    ]
