# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app06', '0011_auto_20160317_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app06.Article')),
            ],
        ),
    ]
